---
apiVersion: v1
# https://kubernetes.io/docs/concepts/services-networking/service
kind: Service
metadata:
  name: {{ include "application.name" . }}
  labels:
    app: {{ include "application.name" . }}
spec:
  selector:
    app: {{ include "application.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.httpPort }}
      targetPort: 8080
